---
title: Workshop Program
---

# ℹ️ Event Details

## **Collaborative Workshop on AI in Medicine**

- **Date:** Tuesday 18 March. 2:30pm - 5:30pm
- **Location:**
  - LRT 608A+B, I-X, 6th Floor I-HUB (Translation & Innovation Hub)
  - Imperial College White City Campus
  - 84 Wood Lane
  - London
  - W12 0BZ
  - [Location Map](https://maps.app.goo.gl/7frVbSAWWfQgtm757)
- **How to Reach the Event**:
  - [Directions to the White City Campus](https://www.imperial.ac.uk/white-city-campus/about-us/how-to-find-us/)
  - On arrival at the I-Hub, reception will give you access to the lifts to 
  reach the 6th floor. Please follow signs to LRT 608A+B
  
## 🗓 Schedule

- **Welcome & Introductions (2:30 – 2:45 PM)**  
  - Opening remarks and workshop objectives.
  - Overview of AI in medicine and interdisciplinary collaboration.

- **Who’s in the Room? (2:45 – 3:00 PM)**  
  - Participant introductions to highlight expertise and shared interests.
  - Icebreaker activity to encourage engagement.

- **Breakout Working Groups (3:00 – 4:00 PM)**  
  - Participants form groups based on shared interests.
  - Internal 1-minute presentations on research background and project ideas.
  - Brainstorming sessions to identify potential research collaborations and funding opportunities.

- **Group Sharing & Discussion (4:00 – 4:30 PM)**  
  - Groups share key insights and proposed collaborations.
  - Facilitated discussion to identify common themes and cross-group synergies.

- **Facilitated Networking (4:30 – 5:15 PM)**  
  - Participants connect based on shared interests.
  - Open discussions to explore potential interdisciplinary projects.

- **Closing Remarks (5:15 – 5:30 PM)**  
  - Summary of key insights and next steps.
  - Opportunities for ongoing collaboration.

- **Networking Reception (5:30 PM onwards)**  
  - Informal discussions over drinks and refreshments.
  - Further opportunity to build collaborations in a relaxed setting.

---
